development:
  adapter: postgresql
  encoding: unicode
  database: social_test_development
  host: localhost
  pool: 5
  username: social
  password: social

test:
  adapter: postgresql
  encoding: unicode
  database: social_demo_test
  host: localhost
  pool: 5
  username: social
  password: social

production:
    adapter: postgresql
    encoding: unicode
    database: social_demo_production
    host: localhost
    pool: 5
    username: social
    password: social
