common: &common
  adapter: postgresql
  username: social-demo
  password: social-demo # from psql setup, see Postgresql

development:
  <<: *common
  database: myapp_development

test:
  <<: *common
  database: myapp_test

production:
  <<: *common
  database: myapp_production